### ISSUE TITLE
PA Review: Categories

### ISSUE THREAD

**Issue by reidjs** [reidjs/eventbike#2]
- [x] Seed with a few different categories 
- [x] All events have a category by default (misc)
- [x] Events can be filtered by category. Requests can be sent to specify that slice of the database to be sent to front end. 
- [x] Categories show up on the sidebar of the events index.
- [x] On the index page, if a category is not selected then a list of 'popular' events should be shown. 
- [ ] STRETCH GOAL: Tags instead of categories.

**Comment by s-pangburn** [comment]
Looks good! 👍
