### ISSUE TITLE
PA Review: Bookmark Events

### ISSUE THREAD

**Issue by reidjs** [reidjs/eventbike#3]
- [x] Users can bookmark events by clicking a button
- [x] Events that a user has bookmarked will show a link to the event on their personal show page.
- [x] ~~Event show page will show a list of the users that have bookmarked the event~~

**Comment by reidjs** [comment]
I crossed out the third because that has been replaced by registrations, which makes a lot more sense to me.

**Comment by s-pangburn** [comment]
Great job Reid! I have no feedback for this one! 💯
