### ISSUE TITLE
PA Review: Events

### ISSUE THREAD

**Issue by reidjs** [reidjs/eventbike#4]
- [x] Seeded with motorcycle or bicycle related data. For example: local races, weekly rides, social meet-ups, etc. 
- [x] Users can navigate through events 
- [x] Events on index are paginated 
- [x] Events have a category 
- [ ] Events are infinitely scrollable (STRETCH GOAL)
- [ ] Events are geolocated on the sidebar (STRETCH GOAL)

**Comment by s-pangburn** [comment]
- [ ] Your pagination extends to 4 pages, but only pages 1 and 2 show up.
- [ ] The background of your event show page should be light gray, the way it is on Eventbrite (observe the lower-left corner):
![screen shot 2017-11-30 at 2 19 47 pm](https://user-images.githubusercontent.com/8031316/33458068-950e90c4-d5d9-11e7-87dc-48721fa6a65a.png)
^ This color right here
Would help delineate the edges of the box.
- [ ] Event creation page should be adequately styled.

**Comment by reidjs** [comment]
Fixed

**Comment by s-pangburn** [comment]
👍
